# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: threat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'threat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cthreat.proto\x12\x10sentinel.threats\"\x9d\x01\n\x0bThreatAlert\x12\x11\n\tthreat_id\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65tector_node_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x13\n\x0bthreat_type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x0b\n\x03lat\x18\x06 \x01(\x01\x12\x0b\n\x03lon\x18\x07 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x08 \x01(\x01\"u\n\tThreatBid\x12\x11\n\tthreat_id\x18\x01 \x01(\t\x12\x16\n\x0e\x62idder_node_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x11\n\tbid_score\x18\x04 \x01(\x02\x12\x17\n\x0fproposed_action\x18\x05 \x01(\t\"j\n\rThreatConfirm\x12\x11\n\tthreat_id\x18\x01 \x01(\t\x12\x1c\n\x14\x63onfirmed_by_node_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x15\n\ris_authorized\x18\x04 \x01(\x08\x42&Z$sentinel-edge-agent/internal/mesh/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'threat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$sentinel-edge-agent/internal/mesh/pb'
  _globals['_THREATALERT']._serialized_start=35
  _globals['_THREATALERT']._serialized_end=192
  _globals['_THREATBID']._serialized_start=194
  _globals['_THREATBID']._serialized_end=311
  _globals['_THREATCONFIRM']._serialized_start=313
  _globals['_THREATCONFIRM']._serialized_end=419
# @@protoc_insertion_point(module_scope)
