// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: threat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThreatId       string                 `protobuf:"bytes,1,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	DetectorNodeId string                 `protobuf:"bytes,2,opt,name=detector_node_id,json=detectorNodeId,proto3" json:"detector_node_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ThreatType     string                 `protobuf:"bytes,4,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"` // e.g., "GPS_SPOOFING", "MOTOR_IMBALANCE"
	Confidence     float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Lat            float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon            float64                `protobuf:"fixed64,7,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt            float64                `protobuf:"fixed64,8,opt,name=alt,proto3" json:"alt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreatAlert) Reset() {
	*x = ThreatAlert{}
	mi := &file_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatAlert) ProtoMessage() {}

func (x *ThreatAlert) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatAlert.ProtoReflect.Descriptor instead.
func (*ThreatAlert) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatAlert) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *ThreatAlert) GetDetectorNodeId() string {
	if x != nil {
		return x.DetectorNodeId
	}
	return ""
}

func (x *ThreatAlert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ThreatAlert) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *ThreatAlert) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatAlert) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ThreatAlert) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ThreatAlert) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

type ThreatBid struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThreatId       string                 `protobuf:"bytes,1,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	BidderNodeId   string                 `protobuf:"bytes,2,opt,name=bidder_node_id,json=bidderNodeId,proto3" json:"bidder_node_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BidScore       float32                `protobuf:"fixed32,4,opt,name=bid_score,json=bidScore,proto3" json:"bid_score,omitempty"`                 // Risk-aware, energy-aware score
	ProposedAction string                 `protobuf:"bytes,5,opt,name=proposed_action,json=proposedAction,proto3" json:"proposed_action,omitempty"` // e.g., "INTERCEPT", "PATROL"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreatBid) Reset() {
	*x = ThreatBid{}
	mi := &file_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatBid) ProtoMessage() {}

func (x *ThreatBid) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatBid.ProtoReflect.Descriptor instead.
func (*ThreatBid) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatBid) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *ThreatBid) GetBidderNodeId() string {
	if x != nil {
		return x.BidderNodeId
	}
	return ""
}

func (x *ThreatBid) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ThreatBid) GetBidScore() float32 {
	if x != nil {
		return x.BidScore
	}
	return 0
}

func (x *ThreatBid) GetProposedAction() string {
	if x != nil {
		return x.ProposedAction
	}
	return ""
}

type ThreatConfirm struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ThreatId          string                 `protobuf:"bytes,1,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	ConfirmedByNodeId string                 `protobuf:"bytes,2,opt,name=confirmed_by_node_id,json=confirmedByNodeId,proto3" json:"confirmed_by_node_id,omitempty"`
	Timestamp         int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsAuthorized      bool                   `protobuf:"varint,4,opt,name=is_authorized,json=isAuthorized,proto3" json:"is_authorized,omitempty"` // HitL confirmation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThreatConfirm) Reset() {
	*x = ThreatConfirm{}
	mi := &file_threat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatConfirm) ProtoMessage() {}

func (x *ThreatConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatConfirm.ProtoReflect.Descriptor instead.
func (*ThreatConfirm) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{2}
}

func (x *ThreatConfirm) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *ThreatConfirm) GetConfirmedByNodeId() string {
	if x != nil {
		return x.ConfirmedByNodeId
	}
	return ""
}

func (x *ThreatConfirm) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ThreatConfirm) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

var File_threat_proto protoreflect.FileDescriptor

const file_threat_proto_rawDesc = "" +
	"\n" +
	"\fthreat.proto\x12\x10sentinel.threats\"\xe9\x01\n" +
	"\vThreatAlert\x12\x1b\n" +
	"\tthreat_id\x18\x01 \x01(\tR\bthreatId\x12(\n" +
	"\x10detector_node_id\x18\x02 \x01(\tR\x0edetectorNodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vthreat_type\x18\x04 \x01(\tR\n" +
	"threatType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\a \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\b \x01(\x01R\x03alt\"\xb2\x01\n" +
	"\tThreatBid\x12\x1b\n" +
	"\tthreat_id\x18\x01 \x01(\tR\bthreatId\x12$\n" +
	"\x0ebidder_node_id\x18\x02 \x01(\tR\fbidderNodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tbid_score\x18\x04 \x01(\x02R\bbidScore\x12'\n" +
	"\x0fproposed_action\x18\x05 \x01(\tR\x0eproposedAction\"\xa0\x01\n" +
	"\rThreatConfirm\x12\x1b\n" +
	"\tthreat_id\x18\x01 \x01(\tR\bthreatId\x12/\n" +
	"\x14confirmed_by_node_id\x18\x02 \x01(\tR\x11confirmedByNodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\ris_authorized\x18\x04 \x01(\bR\fisAuthorizedB&Z$sentinel-edge-agent/internal/mesh/pbb\x06proto3"

var (
	file_threat_proto_rawDescOnce sync.Once
	file_threat_proto_rawDescData []byte
)

func file_threat_proto_rawDescGZIP() []byte {
	file_threat_proto_rawDescOnce.Do(func() {
		file_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_threat_proto_rawDesc), len(file_threat_proto_rawDesc)))
	})
	return file_threat_proto_rawDescData
}

var file_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_threat_proto_goTypes = []any{
	(*ThreatAlert)(nil),   // 0: sentinel.threats.ThreatAlert
	(*ThreatBid)(nil),     // 1: sentinel.threats.ThreatBid
	(*ThreatConfirm)(nil), // 2: sentinel.threats.ThreatConfirm
}
var file_threat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_threat_proto_init() }
func file_threat_proto_init() {
	if File_threat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_threat_proto_rawDesc), len(file_threat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_threat_proto_goTypes,
		DependencyIndexes: file_threat_proto_depIdxs,
		MessageInfos:      file_threat_proto_msgTypes,
	}.Build()
	File_threat_proto = out.File
	file_threat_proto_goTypes = nil
	file_threat_proto_depIdxs = nil
}
