# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fleet.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fleet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66leet.proto\x12\x0esentinel.fleet\"\xf6\x01\n\tNodeState\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x14\n\x0clast_updated\x18\x02 \x01(\x03\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x05 \x01(\x01\x12\x15\n\rbattery_level\x18\x06 \x01(\x02\x12\x0e\n\x06status\x18\x07 \x01(\t\x12@\n\x0cvector_clock\x18\x08 \x03(\x0b\x32*.sentinel.fleet.NodeState.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"\x8b\x01\n\nFleetState\x12\x34\n\x05nodes\x18\x01 \x03(\x0b\x32%.sentinel.fleet.FleetState.NodesEntry\x1aG\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.sentinel.fleet.NodeState:\x02\x38\x01\x42&Z$sentinel-edge-agent/internal/mesh/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fleet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$sentinel-edge-agent/internal/mesh/pb'
  _globals['_NODESTATE_VECTORCLOCKENTRY']._loaded_options = None
  _globals['_NODESTATE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_FLEETSTATE_NODESENTRY']._loaded_options = None
  _globals['_FLEETSTATE_NODESENTRY']._serialized_options = b'8\001'
  _globals['_NODESTATE']._serialized_start=32
  _globals['_NODESTATE']._serialized_end=278
  _globals['_NODESTATE_VECTORCLOCKENTRY']._serialized_start=228
  _globals['_NODESTATE_VECTORCLOCKENTRY']._serialized_end=278
  _globals['_FLEETSTATE']._serialized_start=281
  _globals['_FLEETSTATE']._serialized_end=420
  _globals['_FLEETSTATE_NODESENTRY']._serialized_start=349
  _globals['_FLEETSTATE_NODESENTRY']._serialized_end=420
# @@protoc_insertion_point(module_scope)
